smashingboxes/taperole

roles/database_load/tasks/db_reset.yml
roles/database_load/tasks/main.yml

When you are provisioning/deploying to multiple servers. run_once will run these commands on only one server
http://docs.ansible.com/playbooks_delegation.html#run-once

Remove uses of run_once

---

requirements.yml
roles/backend_install_essentials/meta/main.yml

Allows to use memcached to enable caching using dalli.

Adds memcached

---

roles/backend_config/tasks/main.yml

There’s no reason to be using settingslogic (or figaro) in Rails 4.1 or beyond, which was released April 8, 2014. I do think it's worth leaving in place but commented, but having to ssh in, create an empty and useless file in order to continue installation seems like it's unnecessary for almost any app going forward.

removes settingslogic (env_config) steps

---

roles/general/tasks/main.yml

There was a typo in the command that updates APT's list of packages.
The typo was fixed.

Fix typo in apt-get update

---

lib/tape/installer.rb

I tried updating glen raven to 1.3, by running `bundle update taperole` then `tape installer install` (as seen in the readme). The second command resulted in this:
````
/Users/dkniffin/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/taperole-1.3.0/lib/tape/installer.rb:105:in `mkdir': uninitialized constant TapeBoxer::Installer::Pathname (NameError)
````
Since we're inside a module (`TapeBoxer`) here, we have to prepend `::` to access global namespace classes.

Fix installer error

---

lib/tape/ansible_runner.rb
roles/deployer_user/tasks/main.yml

+ The `deployer` user seems like more of a non-gendered entity. Language was consistently general, except in two places.
+ I wanted to PR to `taperole` so I can know what greatness tastes like
+ Replaced "his" with "its" where appropriate

Neutral Deployer Pronouns

---

bin/tape
lib/tape/ansible_runner.rb

+ Currently Tape only supports a few built-in Ansible playbooks (`omnibox.yml`, `deploy.yml`) but does not allow for running arbitrary playbooks created for a specific project. 
+ Added the `tape ansible playbook` command and the `--book=PLAYBOOK-PATH` option, which, when used in conjunction, will run a given YML file as a playbook with Tape configuration.
**NOTE**: I've been out of the Ruby game for a while and have no experience working with `optparse`. Ideally, the command could be run as `tape ansible playbook [PLAYBOOK-PATH]` but I don't know how to capture the arguments appropriately.

Run Custom Ansible Playbooks

---

README.md
bin/tape
lib/tape/ansible_runner.rb
lib/tape/installer.rb
templates/base/rake.example.yml

- A lot of apps have one-off rake tasks that need to be run.
- Added a new playbook, `rake.yml`, that can run rake tasks as the deployer.
- Added an interface for the new playbook, `tape ansible rake --task users:rank`
https://github.com/Carrigan/test-tape

Add ability to run rake tasks

---

templates/base/deploy.example.yml

- Currently, to give someone access to deploy, you have to run an `everything`. I don't think that should be the case
- Add the deployer_user role to the deploy example template

Update ssh keys on deploy

---

roles/deployer_user/tasks/keys.yml

- Dev keys weren't working at all. I'm actually confused how nobody noticed it before.
- When `with_fileglob` is given a relative path, it makes it relative to the roles/<rolename>/files/ directory. So that means it was really looking in something like `~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/taperole-1.6.0/roles/deployer_user/files/./dev_keys/*` for the dev keys. Of course that's not right.
- Use `playbook_dir` to get the real path to the dev_keys files.

Fix a dev keys bug

---

README.md

- The README had a lot of old information (rot) and cruft.
- Adds a notice about Tape 1.7 no longer supporting Ubuntu 14
- Updates the readme to reference Ubuntu 16 throughout
- Removes local system requirements
- Removes all of the tutorial content, since:
- We link to a tutorial article
- It's not our responsibility to document how Digital Ocean works

Removes a chunk of the readme, touches up other parts

---

lib/taperole/commands/ansible.rb
lib/taperole/core/ansible_runner.rb
roles/database_load/defaults/main.yml
roles/database_load/tasks/db_reset.yml

The current workflow that Tape requires is to map a server 1 to 1 with a branch. For instance, the `development` branch maps to the staging server, and `master` to production. The problem, especially in longer running projects, is that when large features are introduced into development, they can often block smaller features or bug fixes until the large feature has been fully QA accepted. This often leads to larger, riskier deploys to production.
There is an alternate way of branching that I was introduced to at the end of our Weaveup engagement that solves this problem. Instead of the flow `Open PR -> Code Review -> Merge -> QA from development`, the flow changes to `Open PR -> Code Review -> QA directly from feature or bugfix branch -> Merge`. This has the following advantages:
- Your …

Allow alternative git workflow

---

roles/nginx/tasks/main.yml

Remove cd
I think this was messing up the `creates` param which should make this command idempotent.

Only create dhparam if file does not exist

---

roles/deployer_user/tasks/keys.yml
roles/dev_keys/tasks/main.yml
templates/base/deploy.example.yml
templates/base/omnibox.example.yml

I recently added the `deployer_user` role to the `deploy.yml` playbook, so that dev_keys would be deployed on each deployment. That started causing this error:
```
TASK [deployer_user : Copy of root ssh keys] ***********************************
fatal: [138.197.27.240]: FAILED! => {"changed": true, "cmd": ["cp", "/root/.ssh/authorized_keys", "/home/deployer/.ssh/authorized_keys"], "delta": "0:00:00.003396", "end": "2017-01-04 20:49:46.822555", "failed": true, "rc": 1, "start": "2017-01-04 20:49:46.819159", "stderr": "cp: cannot stat '/root/.ssh/authorized_keys': Permission denied", "stdout": "", "stdout_lines": [], "warnings": []}
```
That's because it was trying to more steps than just copying dev_keys. It was also trying to copy root's `authorized_keys`, which deployer didn't have …

Move deployment of dev_keys out of deployer_user role

---

roles/nginx/templates/nginx_puma.j2

Using `force_ssl` in Rails causes a redirect loop on the server without this header set
Set the `X-Forwarded-Proto` header

Set X-Forwarded-Proto Header in nginx

---

README.md

Because setting up LetsEncrypt wasn't obvious
Because others will likely run into the same issue
Added documentation on how to configure LetsEncrypt with multiple hostnames

Add documentation for LetsEncrypt config

---

roles/letsencrypt/tasks/main.yml

* Use the letsencrypt renew-hook to restart nginx on renew
* Nginx must be restarted when a certificate is renewed

Restart nginx when certbot renews certificate

---

roles/nginx/tasks/main.yml
roles/puma_install/templates/puma_init.j2

- Ran into this issue with #137 
- This fixes the puma init script so that it doesn't cause `apt-get upgrade` to fail (which in turn causes a whole host of other things to fail)

Adds init info to fix apt-get upgrade and other related stuff

---

roles/letsencrypt/tasks/main.yml

* Use --pre-hook to stop nginx before cert renew
* Suggested by [this Let's Encrypt thread](https://community.letsencrypt.org/t/nginx-auto-renewal/30894)
* Renewal will fail if nginx is running because LE needs to have access to port 443 to not be taken by any process (NGINX)

Stop nginx on certbot renew

---

roles/redis/templates/redis.j2

Monit failed to find the redis-server pidfile because it was not at the expected location. After provisioning with the `redis` role, the ` /etc/init.d/redis-server` specifies `PIDFILE=$RUNDIR/redis-server.pid`.
Update the expected redis-server pid location to `/var/run/redis/redis-server.pid`

Update the expected redis-server pidfile

---

roles/general/tasks/swapfile.yml
vars/defaults.yml

- Ran in to weird non-specific issues during webpack compilation involving large images
- Even though it's possible to bump up the size of the swap file on a per-project basis, there's not much of a reason to have this be a problem that we run in to unexpectedly, so I bumped up the swapfile to 3bg.
- Also changed the swap file role to perform a `swapon` of the swap file if it is not already on -- this helps when adding another swap file on a server that is already provisioned. The previous method would not let an additional swapfile be created if one already existed.

Bump up the default swapfile size because some webpack plugins are heavy

---

roles/ruby/tasks/main.yml

The `ruby` role prints out a warning because `always_run` is deprecated. It's replaced by `check_mode: no` per the ansible docs:
"Prior to version 2.2 only the the equivalent of check_mode: no existed. The notation for that was always_run: yes."
http://docs.ansible.com/ansible/latest/playbooks_checkmode.html
Replace `always_run: yes` with `check_mode: no`

Update deprecated 'always_run: yes' to 'check_mode: no'

---

roles/whenever/tasks/main.yml

- With the current config, whenever fails with this error:
```
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: chdir={{ be_app_path }} bash -lc bundle exec whenever --update-crontab --set environment={{be_app_env}}"
The error appears to have been in '/Users/dkniffin/Repositories/orangecaregroup-portal/taperole/roles/whenever/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Wheneverize
^ here
exception type: <class 'ansible.errors.AnsibleParserError'>
exception: failed at splitting arguments, either an unbalanced jinja2 block or quotes: chdir={{ be_app_path }} bash -lc bundle exec whenever --update-crontab --set environment={{be_app_env}}"
```
- Removed a …

Fix a typo

---

Gemfile.lock
roles/yarn_install/tasks/main.yml
templates/base/provision.example.yml
templates/base/tape_vars.example.yml

We're using yarn by default now, so we should add a role for it.
* Adds `yarn_install` role
* Ran bundle, which updated `tape`
Yarn suggests installing using this method ([docs](https://yarnpkg.com/en/docs/install#linux-tab)):
> Note: Installation of Yarn via npm is generally not recommended. When installing Yarn with Node-based package managers, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps.
> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.
[Source](https://yarnpkg.com/en/docs/install#alternatives-tab)

Adds yarn role

---

roles/frontend_install_essentials/meta/main.yml
templates/base/provision.example.yml

- If `install_yarn` is listed as a separate item in `provision.yml`, it won't be picked up by existing projects, unless they manually add it their `provision.yml`
- Move `install_yarn` to a dependency of `frontend_install_essentials`

Move install_yarn to a dependency of frontend_install_essentials

---

roles/general/meta/main.yml

unattended-upgrades sit around on disk. Over time, they take up a huge amount of disk space. At a certain point, they fill so much space that all apt commands fail & it becomes a pain to recover the server & clear out the old kernels.
Set the `unattended_remove_unused_dependencies` option.
reference: https://github.com/jnv/ansible-role-unattended-upgrades#role-variables

Configure unattended-upgrades to remove unused dependencies
